const cfg=window.WRITING_MANAGER_CONFIG;
const ready=cfg&&cfg.supabaseUrl&&!cfg.supabaseUrl.startsWith('YOUR_');
// Student page must always use an anonymous, in-memory client.
// This prevents a teacher login stored on the same GitHub Pages origin from changing the RLS role here.
const db=ready?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
const essay=document.querySelector('#essay'), count=document.querySelector('#wordCount'), assignment=document.querySelector('#assignment'), promptBox=document.querySelector('#promptBox');
function words(s){return (s.trim().match(/[A-Za-z0-9]+(?:['’-][A-Za-z0-9]+)*/g)||[]).length}
essay.addEventListener('input',()=>count.textContent=`${words(essay.value)} words`);
async function loadAssignments(){if(!db){assignment.innerHTML='<option value="">Supabase未設定</option>';return}const {data,error}=await db.from('writing_assignments').select('*').eq('active',true).order('created_at',{ascending:false});if(error){assignment.innerHTML='<option value="">読み込みエラー</option>';return}assignment.innerHTML='<option value="">課題を選択</option>'+data.map(a=>`<option value="${a.id}" data-prompt="${encodeURIComponent(a.prompt||'')}">${a.title}</option>`).join('')}
assignment.addEventListener('change',()=>{const o=assignment.selectedOptions[0],p=o?.dataset.prompt?decodeURIComponent(o.dataset.prompt):'';promptBox.textContent=p;promptBox.classList.toggle('hidden',!p)});
document.querySelector('#submissionForm').addEventListener('submit',async e=>{e.preventDefault();const msg=document.querySelector('#message'),btn=document.querySelector('#submitBtn');if(!db){msg.textContent='Supabaseを設定してください。';msg.className='message error';return}if(!confirm('この内容で提出しますか？'))return;btn.disabled=true;const payload={assignment_id:assignment.value,class_name:document.querySelector('#className').value.trim(),student_no:Number(document.querySelector('#studentNo').value),student_name:document.querySelector('#studentName').value.trim(),essay:essay.value.trim(),word_count:words(essay.value),status:'submitted'};const {error}=await db.from('writing_submissions').insert(payload);btn.disabled=false;if(error){msg.textContent='提出できませんでした: '+error.message;msg.className='message error'}else{msg.textContent='提出しました。';msg.className='message ok';essay.value='';count.textContent='0 words'}});
loadAssignments();